### ISSUE TITLE
'Cycler' object has no attribute 'by_key'

### ISSUE THREAD

**Issue by alecrimi** [sbebo/joypy#18]
Hi,
I am running the demo from the notebook:

from __future__ import unicode_literals
import joypy
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import cm

iris = pd.read_csv("data/iris.csv")
%matplotlib inline
fig, axes = joypy.joyplot(iris)

and I get this error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'DataFrame' object is not callable
>>> fig, axes = joypy.joyplot(iris)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/joypy/joyplot.py", line 237, in joyplot
    **kwds)
  File "/usr/local/lib/python2.7/dist-packages/joypy/joyplot.py", line 433, in _joyplot
    element_color = _get_color(i, num_axes, j, num_subgroups)
  File "/usr/local/lib/python2.7/dist-packages/joypy/joyplot.py", line 358, in _get_color
    return plt.rcParams['axes.prop_cycle'].by_key()['color'][j]
AttributeError: 'Cycler' object has no attribute 'by_key'

I am using the latest update  and I am using Python 2.7 from Ubuntu

**Comment by alecrimi** [comment]
Solved: the issue is related to Cycler and Matplot lib not to Joypy:
matplotlib 1.5.1 and Cycler 0.9 are required
